
---
title: "Quick Start"
output:
   rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quick Start}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# The dsld Package: Analysis of Discrimination

</br>
</br>
</br>

# What this package is about

Discrimination, be it racial, gender, age or whatever, is often a major
topic, and a natural application of Data Science. This package consists of
graphical and analytical methods toward this end.

The package enables two quite different aspects of discrimination
involving a sensitive variable S:

* The classical issue: Are two individuals, identical in all respects X
  other than the sensitive variable S, treated differently in terms of
  some variable X? For instance, do men and women of the same
  education, occupation and age (X) have the same mean wage?

* Fairness in machine learning (ML): Say we are using an ML method,
  ranging from ordinary linear regression modeling to deep learning, to
  predict a variable Y from variables X. Is that prediction influenced
  by a sensitive variable S.  A credit institution, say, may wish to
  predict whether a loan would be repaid, Y, based on various credit
  numbers X for the applicant. The question is whether that prediction
  is influenced by sensitive variables S such as race and gender.

# Provenance of the package

Many of the functions in the package are wrappers for functions in
base-R or other packages, with the wrappers adding discrimination
analysis-specific features. For example, **dsldLinear** wraps the
standard R linear model function **lm** (via **qeLin**), but adds dummy
variables for the levels of the sensitive variable S, and forms standard
errors for their difference. If say S is race, this enables comparison
between Black and white, Black and Hispanic and so on.

# Associated textbook

The package is paired with a [free Quarto
textbook](https://htmlpreview.github.io/?https://github.com/matloff/dsldBook/blob/main/_book/index.html).
The book is not an extended user manual for the package; instead, it is
a presentation of the underlying concepts, using the package to
illustrate those concepts.,

# Full function list, by category

Type **vignette('Function_list')**.

